const data = {
  products: [
    {
      _id:'1',
      name: "LENOVO IdeaCentre 520 i3 7th Gen",
      category: "COMPUTER",
      image: "/images/p1.jpg",
      price: 1200,
      countInStock: 10,
      brand: "LENOVO",
      description:"Processor: 7th generation Intel Core i3-7020U (2.3 GHz, 3 MB of Cache Memory, Dual Core) - Operating system: FreeDos - RAM memory: 4 GB DDR4 SDRAM - Hard Disk: 1 TB HDD - Graphics Card: Intel HD Graphics with USB 3.0, HDMI, Memory Card Reader, Wifi, Bluetooth and Webcam - Color: Black - Warranty: 1 year",
    },
    {
      _id:'2',
      name: "ACER SWIFT3 SF314 i3 10th Gen",
      category: "LAPTOP",
      image: "/images/p2.jpg",
      price: 1000,
      countInStock: 20,
      brand: "ACER",
      description:'14 "Full HD IPS screen - Processor: Intel® Core ™ i3-10110U (2.1 GHz up to 4.1 GHz, 4 MB cache memory, Dual-Core) - Windows 10 - Memory: 4 GB - Hard drive: 256 GB SSD - Graphics card: Intel HD Graphics, with Wifi and Bluetooth® 5.0 - Fingerprint reader - Backlit keyboard - Color: Gray - Warranty: 1 year',
    },
    {
      _id:'3',
      name: "ASUS S509JA i3 10th Gen",
      category: "LAPTOP",
      image: "/images/p3.jpg",
      price: 2200,
      countInStock: 3,
      brand: "ASUS",
      description:'15.6 "HD LED screen - Processor: Intel Core i3-1005G1 (1.2 Ghz up to 3.4 Ghz, 4 MB cache memory, Dual-Core) - Operating system: Windows 10 - RAM memory: 4 GB DDR4 - Hard disk: 1 TB - Graphics card: Intel HD Graphics - Color: Gray - Warranty: 1 year',
    },
    {
      _id:'4',
      name: "VERSUS VBOOK Quad Core",
      category: "LAPTOP",
      image: "/images/p4.jpg",
      price: 780,
      countInStock: 15,
      brand: "VERSUS",
      description:'Screen: 14.1"(1366x768 pixels) - Processor: Intel CherryTrail T3 Z8350 (1.92Ghz, Quad Core) - Operating system: Windows 10 - Memory: 2GB DDR3 - Hard drive: 32GB - Graphics card: Intel HD Graphics - cameras : 2MP Frontal - Battery: 9000 mAH with Wifi, Bluetooth, memory card - color: Silver - Weight: 1.3 kg - Warranty: 1 year',
    },
    {
      _id:'5',
      name: "HP Pro G3 Dual Core 8Go",
      category: "COMPUTER",
      image: "/images/p5.jpg",
      price: 650,
      countInStock: 55,
      brand: "HP",
      description: '20.7" LED screen - Processor: Intel Pentium Dual Core G5420 (3.8 Ghz, 4MB of Cache Memory) - Operating system: FreeDos - RAM memory: 8GB - Hard Disk: 1TB - Graphics card: Intel UHD 630 - with DVD burner, USB 3.1, HDMI - Warranty: 1 year',
    },
    {
      _id:'6',
      name: "LENOVO V530T G5420 4Go",
      category: "COMPUTER",
      image: "/images/p6.jpg",
      price: 970,
      countInStock: 12,
      brand: "LENOVO",
      description: 'Processor: Pentium Gold G5420 (3.80 GHz, 4 MB of Cache Memory, Dual-Core) - Operating system: FreeDos - RAM memory: 4 GB DDR4-2400 - Hard disk: 1TB - Graphics card: Intel® UHD Graphics 610 with Ethernet, USB, HDMI and VGA - Warranty: 1 year + LENOVO display ThinkVision 21.5"',
    },
  ],
};
export default data;
