const bcrypt = require("bcrypt");

const data = {
  users: [
    {
      name: "Rami Gharbi",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Houssem Bacha",
      email: "bachahoussem92@gmail.com",
      password: bcrypt.hashSync("26061992", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "LENOVO IdeaCentre 520 i3 7th Gen",
      category: "COMPUTER",
      image: "/images/p1.jpg",
      price: 1200,
      countInStock: 10,
      brand: "LENOVO",
      description:"Processor: 7th generation Intel Core i3-7020U (2.3 GHz, 3 MB of Cache Memory, Dual Core) - Operating system: FreeDos - RAM memory: 4 GB DDR4 SDRAM - Hard Disk: 1 TB HDD - Graphics Card: Intel HD Graphics with USB 3.0, HDMI, Memory Card Reader, Wifi, Bluetooth and Webcam - Color: Black - Warranty: 1 year",
    },
    {
      name: "ACER SWIFT3 SF314 i3 10th Gen",
      category: "LAPTOP",
      image: "/images/p2.jpg",
      price: 1000,
      countInStock: 20,
      brand: "ACER",
      description:'14 "Full HD IPS screen - Processor: Intel® Core ™ i3-10110U (2.1 GHz up to 4.1 GHz, 4 MB cache memory, Dual-Core) - Windows 10 - Memory: 4 GB - Hard drive: 256 GB SSD - Graphics card: Intel HD Graphics, with Wifi and Bluetooth® 5.0 - Fingerprint reader - Backlit keyboard - Color: Gray - Warranty: 1 year',
    },
    {
      name: "ASUS S509JA i3 10th Gen",
      category: "LAPTOP",
      image: "/images/p3.jpg",
      price: 2200,
      countInStock: 0,
      brand: "ASUS",
      description:'15.6 "HD LED screen - Processor: Intel Core i3-1005G1 (1.2 Ghz up to 3.4 Ghz, 4 MB cache memory, Dual-Core) - Operating system: Windows 10 - RAM memory: 4 GB DDR4 - Hard disk: 1 TB - Graphics card: Intel HD Graphics - Color: Gray - Warranty: 1 year',
    },
    {
      name: "VERSUS VBOOK Quad Core",
      category: "LAPTOP",
      image: "/images/p4.jpg",
      price: 780,
      countInStock: 15,
      brand: "VERSUS",
      description:'Screen: 14.1"(1366x768 pixels) - Processor: Intel CherryTrail T3 Z8350 (1.92Ghz, Quad Core) - Operating system: Windows 10 - Memory: 2GB DDR3 - Hard drive: 32GB - Graphics card: Intel HD Graphics - cameras : 2MP Frontal - Battery: 9000 mAH with Wifi, Bluetooth, memory card - color: Silver - Weight: 1.3 kg - Warranty: 1 year',
    },
    {
      name: "HP Pro G3 Dual Core 8Go",
      category: "COMPUTER",
      image: "/images/p5.jpg",
      price: 650,
      countInStock: 55,
      brand: "HP",
      description: '20.7" LED screen - Processor: Intel Pentium Dual Core G5420 (3.8 Ghz, 4MB of Cache Memory) - Operating system: FreeDos - RAM memory: 8GB - Hard Disk: 1TB - Graphics card: Intel UHD 630 - with DVD burner, USB 3.1, HDMI - Warranty: 1 year',
    },
    {
      name: "LENOVO V530T G5420 4Go",
      category: "COMPUTER",
      image: "/images/p6.jpg",
      price: 970,
      countInStock: 12,
      brand: "LENOVO",
      description: 'Processor: Pentium Gold G5420 (3.80 GHz, 4 MB of Cache Memory, Dual-Core) - Operating system: FreeDos - RAM memory: 4 GB DDR4-2400 - Hard disk: 1TB - Graphics card: Intel® UHD Graphics 610 with Ethernet, USB, HDMI and VGA - Warranty: 1 year + LENOVO display ThinkVision 21.5"',
    },
    {
      name: "LENOVO ThinkPad E14 i5 10th Gen",
      category: "LAPTOP",
      image: "/images/p8.jpg",
      price: 2970,
      countInStock: 20,
      brand: "LENOVO",
      description: '14" Full HD screen - Processor: Intel Core i5-10210U (1.6 GHz, Up to 4.2 GHz, 6 MB cache memory, Quad-Core) - Operating system: FreeDos - Memory: 16 GB - Hard drive: 1 TB - Graphics card: AMD Radeon RX 640 (2GB of dedicated GDDR5 memory) with Wifi and Bluetooth - Color: Black - Warranty: 1 year',
    },
    {
      name: "ACER Aspire 3 A317-51G i5 8th Gen",
      category: "LAPTOP",
      image: "/images/p7.jpg",
      price: 3250,
      countInStock: 25,
      brand: "ACER",
      description: '17.3" HD screen - Processor: Intel Core I5-8265U (1.6 GHz up to 3.9 GHz, 6 MB cache memory, Quad-Core) - Operating System: FreeDos - RAM memory: 8 GB - Hard Disk: 1TB + 128 Go SSD - Graphics card: Nvidia GeForce MX230 (2 Go of dedicated memory) with Wifi and Bluetooth - Color: Black - Warranty: 1 year',
    },
    {
      name: "HP 15 dw2009nk i7 10th Gen",
      category: "LAPTOP",
      image: "/images/p9.jpg",
      price: 3250,
      countInStock: 25,
      brand: "ACER",
      description: 'Screen: 15.6" FULL HD - Processor: Intel Core ™ i7-1065G7 (1.3 GHz up to 3.9 GHz, 8 MB cache memory, Quad-Core) -Operating system: Windows 10 - RAM memory: 8 GB DDR4 - Hard disk: 1 TB HDD - Graphics card: NVIDIA® GeForce® MX330 (2 GB of dedicated memory) - Fingerprint reader - Color: Silver - Warranty: 1 year',
    },
    {
      name: "MSI GF63 i5 10th Gen",
      category: "LAPTOP",
      image: "/images/p10.jpg",
      price: 4800,
      countInStock: 25,
      brand: "MSI",
      description: '15.6" FULL HD screen - Processor: Intel Core i5-10300H (2.5 GHz up to 4.5 GHz, 8 MB cache memory, Quad-Core) - FreeDos - RAM memory: 8 GB DDR4 - Hard drive: 512 GB SSD - Graphics card : NVIDIA GeForce GTX 1650 (Max-Q) with (4 GB of dedicated GDDR5 memory) - Red LED backlit keyboard - Warranty: 2 years',
    },
    {
      name: "Pavilion Laptop 15 dk1001nk i7 10th Gen",
      category: "LAPTOP",
      image: "/images/p11.jpg",
      price: 3980,
      countInStock: 25,
      brand: "PAVILLON",
      description: '15.6" IPS FHD screen - Processor: Intel Core i7-10750H (2.6 GHz up to 5.0 GHz, 12 MB cache memory, Hexa-Core) - Windows 10 Home - RAM memory: 8 GB DDR4 - Hard drive: 512 GB SSD - Graphics card: NVIDIA GeForce GTX 1650 (4GB of dedicated GDDR5 memory) with Wifi and Bluetooth - Backlit keyboard - Warranty: 1 year',
    },
    {
      name: "MSI i7 10th Gen 8Go 512Go SSD",
      category: "LAPTOP",
      image: "/images/p12.jpg",
      price: 4750,
      countInStock: 22,
      brand: "MSI",
      description: '15.6" Full HD screen - Processor: Intel Core i7-1075H (2.6 GHz up to 5.0 GHz, 12MB of cache memory, Hexa-Core) - Free Dos - RAM memory: 8 GB DDR4 - Hard disk: 512 GB SSD - Graphics card: Nvidia ™ GeForce® GTX 1650 (4 GB of dedicated memory), with Wifi, Bluetooth - Backlit keyboard - Warranty: 2 years',
    },
    {
      name: "ASUS S509JA-BR650T i3 10th Gen",
      category: "LAPTOP",
      image: "/images/p13.jpg",
      price: 1320,
      countInStock: 22,
      brand: "ASUS",
      description: '15.6" HD LED screen - Processor: Intel Core i3-1005G1 (1.2 Ghz up to 3.4 Ghz, 4 MB cache memory, Dual-Core) - Operating system: Windows 10 - RAM memory: 4 GB DDR4 - Hard disk: 1 TB - Graphics card: Intel HD Graphics with USB 3.0, HDMI, Card Reader - Color: Blue - Warranty: 1 year',
    },
    {
      name: "MSI GE66 i7 10th Gen",
      category: "LAPTOP",
      image: "/images/p14.jpg",
      price: 6900,
      countInStock: 34,
      brand: "MSI",
      description: '15.6" FULL HD screen - Processor: Intel Core i7-10750H (2.6 GHz up to 5.00 GHz, 12 MB cache memory, Hexa-Core) - FreeDos - RAM memory: 16 GB - Hard drive: 1TB SSD - Graphics card: NVIDIA GeForce RTX 2070 (8 GB of dedicated memory) - Color: Gray - Warranty: 2 years',
    },
    {
      name: "ASUS ZenBook i7 10th Gen",
      category: "LAPTOP",
      image: "/images/p15.jpg",
      price: 7100,
      countInStock: 14,
      brand: "ASUS",
      description: '15.6" UHD Touch Screen - Processor: Intel Core i7-10750H (2.60 GHz up to 5.00 GHz, 12MB of cache memory, Hexa-Core) - Windows 10 - RAM memory: 16 GB DDR4 - Hard disk: 512 GB SSD - Graphics card: Nvidia GeForce RTX 2060 (6 GB of dedicated memory), with Wifi, Bluetooth - Chiclet keyboard - Warranty: 2 years + ScreenPad Plus & Stylus',
    },
    {
      name: "DELL XPS 7390 2EN1 i7 10th Gen",
      category: "LAPTOP",
      image: "/images/p16.jpg",
      price: 4990,
      countInStock: 19,
      brand: "DELL",
      description: '13.4" Ultra HD Touch Screen - Processor: Intel Core i7-1065G7 (1.3 GHz up to 3.9 GHz, 8 MB cache memory, Quad-Core) - Windows 10 Pro - RAM memory: 16 GB DDR4 - Hard drive: 256 GB SSD - Graphics card: Intel® HD Graphics with WiFi and Bluetooth - Backlit keyboard - Color: Silver - Warranty: 1 year',
    },
    {
      name: "ASUS ROG STRIX G512LV i7 10th Gen",
      category: "LAPTOP",
      image: "/images/p17.jpg",
      price: 4620,
      countInStock: 15,
      brand: "ASUS",
      description: 'Screen 15.6" FULL HD 240HZ - Processor: Intel Core i7-10870H (2.20GHz up to 5.00GHz, 16MB of cache memory, Octa-core) - Operating system: Windows 10 Home - RAM memory: 16GB - Hard disk: 512GB SSD - Graphics card: Nvidia GeForce RTX 2060 (6GB of dedicated memory) with Wifi - Bluetooth - Digital touchpad - Color: Black - Warranty: 2 years',
    },
    {
      name: "HP EliteBook 830 G5 i7 8th Gen",
      category: "LAPTOP",
      image: "/images/p18.jpg",
      price: 3660,
      countInStock: 27,
      brand: "HP",
      description: 'Screen: 13.3" FULL HD (1920 x 1088 Pixels) - Processor: 8th Generation Intel Core i7-8550U (1.8 GHz, up to 4.0 GHz, 8 MB cache, Quad-Core) - Operating system: Windows 10 Pro - RAM memory: 8 GB SDRAM DDR4-2400 - Hard disk: 256 GB SSD - Graphics card: Intel HD Graphics with USB 3.1, HDMI, RJ-45 - Bluetooth 4.2 - Weight: 1.33 Kg - Color: Silver - Warranty: 3 years',
    },
    {
      name: "HP ENVY 15-ep0088nf i5 10th Gen",
      category: "LAPTOP",
      image: "/images/p19.jpg",
      price: 4399,
      countInStock: 27,
      brand: "HP",
      description: '15.6" FULL HD IPS screen - Processor: Intel Core i5-10300H (2.5 GHz up to 4.5 GHz, 8 MB cache memory, Quad-Core) - Windows 10 - RAM memory: 16 GB DDR4 - Hard drive: 512 GB SSD - Graphics card: NVIDIA GeForce GTX1650Ti (4 GB of dedicated memory) with WiFi and Bluetooth - Color: Silver - Warranty: 1 year',
    },
    {
      name: "ANTEC i5 10th Gen 8GB 240GB SSD Desktop Gaming PC ",
      category: "COMPUTER",
      image: "/images/p30.jpg",
      price: 1820,
      countInStock: 15,
      brand: "ANTEC",
      description:"Processor: Intel Core i5-10400F (2.9 GHz up to 4.30 GHz, 12 MB cache memory, Hexa-core) - FreeDos - RAM memory: 8G 3000MHZ CL16 - Hard Disk: 240Go SSD - Motherboard: B460M-A PRO - Card graphics: Nvidia GeForce GTX 1650 (4GB of Dedicated Memory) - NJOY N TITAN + 500W 80+ BRONZE box - Warranty: 1 year",
    },
    {
      name: "ACER Veriton S2660G i7 8th Gen 8GB 1TB",
      category: "COMPUTER",
      image: "/images/p31.jpg",
      price: 1769,
      countInStock: 18,
      brand: "ACER",
      description:'Processor: Intel Core i7-8700 (3.20 GHz up to 3.60 GHz Turbo, 12 MB of Cache Memory, 6 Cores) - Operating system: FreeDos - RAM memory: 8 GB DDR4 - Hard Disk: 1TB - Graphics card: Intel HD Graphics with Ethernet, USB 3.1 Gen 1, USB 3.1 Gen 2, HDMI, VGA, DisplayPort - Warranty: 1 year',
    },
    {
      name: "ADVANCE i5 9th Gen Gaming Desktop PC 16GB 1TB + 256GB SSD",
      category: "COMPUTER",
      image: "/images/p32.jpg",
      price: 2059,
      countInStock: 3,
      brand: "ADVANCE",
      description:'Processor: Intel Core i5-9400F (2.9 GHz up to 4.10 GHz, 9 MB cache memory, Hexa-core) - Operating System: FreeDos - RAM memory: 16 GB DDR4 2666 MHz - Hard Disk: 1TB + 256GB SSD - Graphics card: Nvidia GeForce GTX 1650 super (4GB of Dedicated Memory) - Warranty: 1 year',
    },
    {
      name: "ACER Veriton S2660G i7 8th Gen 8GB 1TB Desktop PC",
      category: "COMPUTER",
      image: "/images/p33.jpg",
      price: 2029,
      countInStock: 15,
      brand: "ACER",
      description:'Screen: 21.5 "LED Full HD - Processor: Intel Core i7-8700 (3.20 GHz up to 3.60 GHz Turbo, 12 MB of Cache Memory, 6 Cores) - Operating system: FreeDos - RAM memory: 8 GB DDR4 - Hard Disk: 1TB - Graphics card: Intel HD Graphics with Ethernet, USB 3.1 Gen 1, USB 3.1 Gen 2, HDMI, VGA, DisplayPort - Warranty: 1 year',
    },
    {
      name: "HP ProDesk 400 G6 i5 9th Gen Desktop PC 4Go 1TB",
      category: "COMPUTER",
      image: "/images/p34.jpg",
      price: 2339,
      countInStock: 21,
      brand: "HP",
      description: '20.7 "LED screen (1920 x 1080) - Processor: Intel Core i5-9500 9th Generation (3.0 GHz, Up To 4.4 GHz, 9MB of Cache Memory, Hexa-Core) - Operating system: Windows 10 Pro - RAM memory: 4 GB SDRAM DDR4-2666 - Hard drive: 1 TB HDD, 7200 rpm - Graphics card: Intel® HD Graphics with USB 3.1, USB 2.0 and VGA - Warranty: 1 year',
    },
    {
      name: "HP Pavilion Gamer TG01-1006nk i5 10th Gen Desktop PC 16GB 1TB + 128GB SSD",
      category: "COMPUTER",
      image: "/images/p35.jpg",
      price: 2649,
      countInStock: 12,
      brand: "HP",
      description: 'Processor: Intel Core i5-10400 10th Generation (2.90 GHz, Up To 4.30 GHz, 12MB of Cache Memory, Hexa-Core) - Operating system: Windows 10 - RAM memory: 16 GB SDRAM DDR4-2666 - Hard drive: 1 TB + 128 GB SSD, 7200 rpm - Graphics card: NVIDIA® GeForce® RTX 2060 (6 GB of dedicated GDDR6 memory) with HP 3-in-1 Media Card Reader, USB 2.0 and HDMI - Dimensions : 15.54 x 30.7 x 33.74 cm - Weight: 5.96 kg - Warranty: 1 year',
    },
    {
      name: "ALL IN ONE Desktop PC ASUS ZN242GDK I5 8th Gen 12GB 1TB + 256SSD",
      category: "COMPUTER",
      image: "/images/p36.jpg",
      price: 2939,
      countInStock: 8,
      brand: "ASUS",
      description: '23.8 "HD LED screen - Intel® Core i5-8300H processor (2.3 GHz Up to 4.0 Ghz Turbo, 8 MB cache memory, Quad-Core), Operating system: Windows 10 - 12 GB DDR4 1600 MHz RAM, Hard Disk 1TB SATA + 256GB SSD, NVIDIA GeForce GTX 1050 Graphics Card (4GB GDDR5 Dedicated Memory) with USB 3.1, USB 2.0, HDMI, WiFi, Integrated WebCam - Warranty: 1 year',
    },
    {
      name: "Desktop PC All In One HP Pavilion 24-k0003nk i7 10th Gen 8GB 1TB",
      category: "COMPUTER",
      image: "/images/p37.jpg",
      price: 3799,
      countInStock: 7,
      brand: "HP",
      description: '23.8 "Full HD IPS Touch Screen - Processor: Intel® Core i7-10700T (2.0 GHz, up to 4.4 GHz, 16 MB cache memory, Octa-Core) - Operating system: Windows 10 Family 64 - RAM memory: 8 GB DDR4-2666 SDRAM - Hard Disk: 1TB SATA, 7200 rpm - Graphics card: NVIDIA GeForce MX350 (2 GB of dedicated GDDR5 memory) with Wifi, Bluetooth 4.2 and 3-in-1 memory card reader - Color: White - Warranty: 1 year',
    },
    {
      name: "LENOVO P410 E5-1620V4 8GB 1TB Workstation",
      category: "COMPUTER",
      image: "/images/p38.jpg",
      price: 3899,
      countInStock: 9,
      brand: "LENOVO",
      description: 'ThinkStaton LENOVO P410 - Form factor: Tower - Processor: Intel Xeon E5-1620 v4 (3.5 GHz Up to 3.8 GHz, 10 MB cache, 4 cores), Operating system: Windows 7 Pro 64 Bits / Windows 10 Pro - Memory: 8GB DDR4-2400 SDRAM (1 x 8GB) - Hard Disk: 1TB SATA (7200 rpm) - Chipset: Intel C612 Platform Controller Hub - Without Graphics Card - Network Interface: Intel i218LM (1 x Gigabit Ethernet Port) - Connectors: 6 x USB 3.0, 2 x USB 2.0, 1 x Rj45, 2 x PS / 2, 1 x Serial, 1 x Card reader 9 In 1, 1 x Audio input / output, 1 x Microphone input - DVD- RW - Power supply: 450W - Guarantee: 3 years',
    },
    {
      name: "All In One Desktop PC DELL 5477 i7 8th Gen 16GB 1TB + 128 SSD",
      category: "COMPUTER",
      image: "/images/p39.jpg",
      price: 3919,
      countInStock: 13,
      brand: "DELL",
      description: '23.8 "IPS Full HD screen - Processor: 8th Gen Intel Core i7-8700T (2.4 GHz, up to 4.0 GHz, 12 MB cache memory, Hexa-Core) - Operating system: Linux - RAM memory : 16 GB - Hard Disk: 1TB + 128 SSD - Graphics Card: Intel HD Graphics with Keyboard and Mouse, DVI, HDMI, Wifi, Ethernet, Bluetooth 4.2 - Warranty: 1 year',
    },
    {
      name: 'Apple iMac 21.5" i5 4Go 1To',
      category: "COMPUTER",
      image: "/images/p40.jpg",
      price: 4529,
      countInStock: 2,
      brand: "APPLE",
      description: 'Screen: 21.5 "IPS LED Full HD (1920 x 1080 pixels) - Processor: Intel Core i5 (2.3 GHz up to 3.6 GHz Turbo, Dual-Core), Operating system: Apple Mac OS X Sierra, RAM memory: 4 GB DDR4 21330 MHz, Hard Disk: 1 TB, Graphics Card: Intel Iris Plus Graphics 640 with Thunderbolt 3, DisplayPort, USB 3.1, HDMI, VGA, DVI, Card Reader - 1 year warranty',
    },
    {
      name: "PHOENIX i7 9th Gen 32GB 1TB + 256GB SSD Desktop Gaming PC - Black",
      category: "COMPUTER",
      image: "/images/p41.jpg",
      price: 4599,
      countInStock: 1,
      brand: "PHOENIX",
      description: 'Processor: Intel Core i7-9700K 9th Generation (3.6 GHz up to 4.9 GHz, 12 MB cache memory, Octa-Core) - Operating System: FreeDos - RAM memory: 32 GB - Hard Disk: 1TB + 256 GB SSD - Graphics card: Nvidia GeForce RTX 2070 Super (6GB GDDR5 Dedicated Memory) - Warranty: 1 year',
    },
    {
      name: "HP OMEN GT12-0001nk i9 10th Gen Gaming Desktop PC 16GB 2TB + 256GB SSD (29B43EA)",
      category: "COMPUTER",
      image: "/images/p42.jpg",
      price: 6199,
      countInStock: 6,
      brand: "HP",
      description: '10th Generation Intel® Core ™ i9-10900 processor (2.8 GHz, up to 5.2 GHz, 20 MB cache memory, 10 cores) - Operating system: Windows 10 - RAM memory: 16 GB SDRAM DDR4-2933 - Hard disk: 2 TB, 7200 rpm + 256 GB SSD - Graphics card: NVIDIA GeForce RTX 2080 Super (8 GB of dedicated GDDR6 memory) with Wifi, Bluetooth, Ethernet - Warranty: 1 year',
    },
    {
      name: 'SAMSUNG 24 "LED FULL HD Display (S24F350FHM)',
      category: "SCREEN",
      image: "/images/p43.jpg",
      price: 385,
      countInStock: 51,
      brand: "SAMSUNG",
      description: 'SAMSUNG screen - Screen size: 24 "PLS LED FULL HD - Resolution: 1920 x 1080 - Brightness: 250cd / m² - Contrast ratio: 1000: 1 (typical - Response time: 2 (GTG) ms, Type of panel: TN, connectors: 1 x HDMI, 1 x VGA, Compatible with: Windows, Mac, Built-in function: Game mode (AMD FreeSync), Eye Saver mode, Flicker Free technology - Warranty: 1 year',
    },
    {
      name: 'LENOVO 23.8 "screen (62A8KAT1EU)',
      category: "SCREEN",
      image: "/images/p44.jpg",
      price: 389,
      countInStock: 31,
      brand: "LENOVO",
      description: 'LENOVO screen - Screen size: 23.8 "FULL HD - Resolution: 1920 x 1080 px - Screen format: 16: 9 - Contrast ratio: 1000: 1 - Brightness: 250 cd / m2 - Response time: 4 ms (extreme mode) / 6 ms (normal mode) - Viewing angle (H / V): 178/178 - Connectors: HDMI, VGA - Warranty: 3 years',
    },
    {
      name:' HP 24 "FHD Monitor (9SV73AA)',
      category: "SCREEN",
      image: "/images/p45.jpg",
      price: 399,
      countInStock: 14,
      brand: "HP",
      description: 'HP V24 screen - Screen size: 24 "FULL HD - Resolution: 1920 x 1080 Pixels at 60Hz - Aspect ratio: 16: 9 - Brightness: 250 cd / m² - Contrast ratio: 1000: 1 - Time response (On / off): 1 ms - Viewing angle (horizontal & vertical): 170 ° - Connectors: HDMI and VGA - Warranty: 1 year',
    },
    {
      name: 'DAHUA 23.8 "LED FULL HD display (LM24-F211)',
      category: "SCREEN",
      image: "/images/p46.jpg",
      price: 399,
      countInStock: 17,
      brand: "DAHUA",
      description: 'DAHUA screen - Screen size 23.8 "LED FULL HD - Resolution: 1920 x 1080 pixels - Brightness: 250 cd / m2 - Contrast: 1000: 1 - Viewing angle: 178 ° / 178 ° (vertical / horizontal - response: 14 ms - Connectors: 1x VGA, 1 x HDMI, 1 x Audio - Dimensions: 540.6 x 322.6 x 50.1 mm - Warranty: 1 year',
    },
    {
      name: 'SAMSUNG 24 "LED FULL HD Curved Display (LC24F390FH)',
      category: "SCREEN",
      image: "/images/p47.jpg",
      price: 419,
      countInStock: 9,
      brand: "SAMSUNG",
      description: 'SAMSUNG Curved Screen - Screen Size: 24 "LED FULL HD - Resolution: 1920 x 1080 pixels - Brightness: 250 cd / m2, Response Time: 4 ms - Curvature: 1800R - Aspect Ratio: 16: 9 - Type d " display: Virginie - Connectors: HDMI-VGA - Warranty: 1 year ',
    },
    {
      name: 'HP 27f 27 "FULL HD Monitor (2XN62AA)',
      category: "SCREEN",
      image: "/images/p48.jpg",
      price: 589,
      countInStock: 4,
      brand: "HP",
      description: 'HP 27f screen - Screen size: 27 "FULL HD IPS with LED backlight - Resolution: 1920x1080 - Aspect ratio: 16: 9 - Brightness: 300 cd / m² - Contrast ratio: 10,000,000: 1 - Angle of vision: 178 ° H / 178 ° V - Response time: 5ms - Connectors: VGA, HDMI, Audio input / output - Color: White & Black - Warranty: 1 year',
    },
    {
      name: 'SAMSUNG 27 "LED FULL HD Curved Display (LC27F390)',
      category: "SCREEN",
      image: "/images/p49.jpg",
      price: 599,
      countInStock: 16,
      brand: "SAMSUNG",
      description: 'SAMSUNG Curved Screen - Screen Size: 27 "VA LED FULL HD - Native Resolution: 1920 x 1080, Brightness: 250 cd / m² - Response Time: 4 ms - Screen Curvature: 1800R - Contrast Ratio: 3000 / 1 (Type) - AMD FreeSync, Eco Saving Plus, Eye Saver and Flicker Free Game Mode - Connectors: 1 x HDMI, 1 x VGA - Energy Class: A - Dimensions: 62.3 x 46.3 x 18.1 cm - Weight: 5.5 kg - Warranty: 1 year',
    },
    {
      name: 'MILLENIUM MD24 PRO 23.6 "Full HD Gaming Monitor (MD24PRO)',
      category: "SCREEN",
      image: "/images/p50.jpg",
      price: 629,
      countInStock: 3,
      brand: "MILLENIUM",
      description: 'MILLENIUM MD24 PRO Gaming Monitor - Screen size: 23.6 "Full HD - Resolution: 1920 x 1080 px - Aspect ratio: 16: 9 - Brightness: 250 cd / m² - Contrast Ratio: 3000: 1 - Angle of vision: 178 ° / 178 ° V - Response time: 4ms - Tilt: -5 to + 15 ° - Screen scanning frequency: 144 Hz - Curved -Adjustable in height - Connectors: 1x Display Port - 2x HDMI - 1 headphone output - Dimensions: 53.8 x 18.4 x 41.2 cm - Weight: 5 kg - Color: Black - Warranty: 1 year',
    },
    {
      name: 'HP 24.5 "FULL HD Gaming Monitor (4JF31AA)',
      category: "SCREEN",
      image: "/images/p51.jpg",
      price: 729,
      countInStock: 14,
      brand: "HP",
      description: 'HP Gaming Monitor - Screen size: 24.5 "FULL HD - Resolution: 1920 x 1080 at 60 Hz - Aspect ratio: 16: 9 - Brightness: 400 cd / m² - Contrast Ratio: 1000: 1 (static ) - Response time: 1 ms - AMD FreeSync ™ - Weight: 4.3 kg - Color: Black - Warranty: 1 year',
    },
    {
      name: 'BENQ ZOWIE 24 "FULL HD screen (XL2411P)',
      category: "SCREEN",
      image: "/images/52.jpg",
      price: 749,
      countInStock: 5,
      brand: "BENQ",
      description: 'BENQ ZOWIE 24" TN LED FULL HD screen - Resolution: 1920 × 10800 px - Image format: 16: 9 - Brightness: 350 cd / m² - Response time: 1 ms - Contrast: 1000: 1 - Maximum vertical frequency: 144 Hz - Power consumption: 45W - AC input power: 90 to 264 VAC, 50/60 Hz - Connectors: 1 x DisplayPort Female, 1 x DVI Female, 1 x HDMI Female, 1 x DVI-I Dual-Link, 1 x 1 x Helmet - Dimensions: 559 (highest) / 429 (lowest) x 570 x 219 mm - Weight: 3.6 kg - Color: Black - Warranty: 1 year',
    },
    {
      name: 'AOC 24 "FULL HD CURVED Gaming Monitor (C24G1)',
      category: "SCREEN",
      image: "/images/p53.jpg",
      price: 749,
      countInStock: 3,
      brand: "AOC",
      description: 'AOC Curved Gaming Display - Screen size 24" FULL HD - Resolution: 1920 x 1080 pixels - Aspect ratio: 16: 9 - Brightness: 250 cd / m² - Contrast: 3000: 1 - Refresh rate: 144 Hz - WLED backlight - Viewing Angle: 178/178 º - Connectors: 2 x HDMI, 1 x DisplayPort 1.2, 1 x VGA, 1 x headphones - Dimensions: 512.8 x 536.9 x 244.9 mm - Weight: 4.5 Kg - Warranty: 1 year',
    },
  ],
};

module.exports = data;
